MyProject/MyProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Tutorial.urls')),
    path('ckeditor5/', include("django_ckeditor_5.urls"))
]

MyProject/Tutorial/urls.py
from django.urls import path
from . import views

# Define a list fo url Patterns

urlpatterns = [
    # To render Welcome msg
    path('', views.home, name = 'home'),

    # To render all the contents in a Topic model/table
    path('<slug:concept_slug>/', views.index, name='index'),

    # to render specific topic
    path('<slug:concept_slug>/<slug:topic_slug>/', views.topic, name='topic'),
    # TODO: have to create a path for every topic in the database maybe, don't forget o mention the same in MyProject/url.py
    # path('post/', views.post, name="post")
    # path('ckeditr')
]

MyProject/Tutorial/models.py
from django.db import models
from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field


# Create your models here.
class Concept(models.Model):
    title = models.CharField(max_length=200)
    tagline = models.CharField(max_length=300, null=True, blank=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True,
                            help_text="URL-friendly identifier; auto-generated")
    draft = models.BooleanField(default=False,
                                help_text="Tick if this topic should remain in draft not show up in live site)")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        # Auto-generate slug from title if blank
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class Topic(models.Model):
    concept = models.ForeignKey(Concept, on_delete=models.CASCADE, related_name='topics')
    order       = models.PositiveIntegerField(help_text="Controls display order")
    title       = models.CharField(max_length=200)
    slug        = models.SlugField(max_length=200, unique=True, blank=True,
                                   help_text="URL-friendly identifier; auto-generated")
    # content = CKEditor5Field()
    content = CKEditor5Field(config_name='default', default='')
    # You can edit the ckeditor text field, dig around
    # The optional config_name parameter should match the key in your CKEDITOR_5_CONFIGS settings.
    # Do the same for the Subtitle model or any other place where you previously used the old CKEditor field. '''
    # has_subtitles = models.BooleanField(default=False)
    draft = models.BooleanField(default=False,
                                help_text="Tick if this topic should remain in draft not show up in live site)")
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['order']

    def save(self, *args, **kwargs):
        # Auto-generate slug from title if blank
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.order}. {self.title}"

class Subtitle(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='subtitles')
    order       = models.PositiveIntegerField(help_text="Controls display order")
    title       = models.CharField(max_length=200)
    slug        = models.SlugField(max_length=200, unique=True, blank=True,
                                   help_text="URL-friendly identifier; auto-generated")
    content = CKEditor5Field(config_name='default', default='')
    draft = models.BooleanField(default=False)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['order']
        unique_together = ['topic', 'slug']

    def save(self, *args, **kwargs):
        # Auto-generate slug from title if blank
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.topic.title} - {self.order}. {self.title}"

MyProject/Tutorial/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget
from .models import Concept, Topic, Subtitle


# Tried to make a html form form to add content in the site but admin page is simple for now
# class ConceptForm(forms.Form):
#     class Meta:
#         model = Topic
#         fields = ['order', 'title', 'slug', 'content', 'has_subtitles']
#
# class SubtitleForm(forms.Form):
#     class Meta:
#         model = Subtitle
#         fields = ['order', 'title', 'slug', 'content']

class ConceptAdminForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditor5Widget(config_name='default'))
    class Meta:
        model = Concept
        fields = '__all__'

class TopicAdminForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditor5Widget(config_name='default'))
    class Meta:
        model = Topic
        fields = '__all__'
        # Automatically adds the slug while entering the title
        prepopulated_fields = {"slug": ("title",)}

class SubtitleAdminForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditor5Widget(config_name='default'))
    class Meta:
        model = Subtitle
        fields = '__all__'
        # Getting an error while adding the multiple subtitles because of form validations
        # because slug will generate the unique url/slug while saving and form validation,
        # are before saving method
        # exclude = ('slug',)  # Remove slug from the form so it isn't validated
        # may be later i need to add auto-populate the slug field in the form itself would
        # work for this!
        # prepopulated_fields = {"slug": ("title",)}

MyProject/Tutorial/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Topic, Subtitle, Concept
# Create your views here.
# To render html pages, to load the database, pass the arguments/data/ to the html page


# def home(request):
#     concepts = Concept.objects.filter(draft=False).order_by('created_at')
#     nav_concepts = concepts
#     return render(request, 'Tutorial/home.html', {
#         "concepts": concepts,
#         "nav_concepts" : nav_concepts,
#         'title': 'Welcome to Tutorial'
#     })

# # To render a Name maybe or a welcome message and button to start
# # def home(request):
# #     return render(request, 'Tutorial/home.html', {
# #         "title": "Welcome to Tutorial"
# #     })

# # To render Contents(title of Topic model/table) of the page
# def index(request, concept_slug):
#     concept = get_object_or_404(Concept, slug=concept_slug, draft=False)
#     topics = Topic.objects.filter(concept=concept, draft=False).order_by('order')

#     concepts = Concept.objects.filter(draft=False).order_by('created_at')
#     nav_concepts = concepts
#     return render(request, 'Tutorial/index.html', {
#         'concept': concept,
#         "topics": topics,
#         "nav_concepts" : nav_concepts,
#     })

# to render specific topic/topic
# it should connect to the index page contents(links)
# those links should dynamically create not hard coded (need to play with GET, POST requests).
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Topic, Subtitle, Concept

def home(request):
    concepts = Concept.objects.filter(draft=False).order_by('created_at')
    nav_concepts = concepts
    return render(request, 'Tutorial/base.html', {
        "concepts": concepts,
        "nav_concepts" : nav_concepts,
        'title': 'Welcome to Tutorial'
    })

def index(request, concept_slug):
    concept = get_object_or_404(Concept, slug=concept_slug, draft=False)
    topics = Topic.objects.filter(concept=concept, draft=False).order_by('order')
    concepts = Concept.objects.filter(draft=False).order_by('created_at')
    nav_concepts = concepts
    return render(request, 'Tutorial/index.html', {
        'concept': concept,
        "topics": topics,
        "nav_concepts" : nav_concepts,
    })

def topic(request, concept_slug, topic_slug):
    current_concept = get_object_or_404(Concept, slug=concept_slug, draft=False)
    topic = get_object_or_404(Topic, slug=topic_slug, concept=current_concept, draft=False)
    topics = Topic.objects.filter(concept=current_concept, draft=False).order_by('order')

    # For sidebar & next/prev
    concept_topics = list(topics)
    previous_topic = None
    next_topic = None

    # For secondary/nav bar concepts
    concepts = Concept.objects.filter(draft=False).order_by('created_at')
    nav_concepts = concepts

    # compute current_topic_index robustly and progress
    current_topic_index = None
    try:
        current_topic_index = concept_topics.index(topic)
        if current_topic_index > 0:
            previous_topic = concept_topics[current_topic_index - 1]
        if current_topic_index < len(concept_topics) - 1:
            next_topic = concept_topics[current_topic_index + 1]
    except ValueError:
        # keep defaults (shouldn't normally happen)
        current_topic_index = 0

    # compute progress percent and textual progress
    total_topics = len(concept_topics) if concept_topics else 0
    if total_topics > 0:
        progress_percent = int(((current_topic_index + 1) / total_topics) * 100)
        current_position = current_topic_index + 1
    else:
        progress_percent = 0
        current_position = 0

    subtitles = topic.subtitles.filter(draft=False).order_by('order')

    context = {
        "nav_concepts": nav_concepts,
        'topics': topics,
        'topic': topic,
        'subtitles': subtitles,
        'concept': current_concept,
        'previous_topic': previous_topic,
        'next_topic': next_topic,
        # NEW: progress + totals for template
        'progress_percent': progress_percent,
        'current_position': current_position,
        'total_topics': total_topics,
    }
    return render(request, 'Tutorial/topic.html', context)
# decorator for verification of admin user
# from django.contrib.admin.views.decorators import staff_member_required
# from .models import Topic
# from .forms import ConceptForm, SubtitleForm
#
# @staff_member_required
# def concept_post(request):
#     if request.method == 'POST':
#         form = ConceptForm(request.POST)
#         if form.is_valid():
#             topic = form.save()
#             return redirect('edit_post', concept_id=topic.id)
#     else:
#         form = ConceptForm()
#     return render(request, 'admin/create_concept.html', {'form':form})
#
#
# @staff_member_required
# def edit_concept(request, concept_id):
#     topic = get_object_or_404(Topic, id=concept_id)
#     if request.method == 'POST':
#         form = ConceptForm(request.POST, instance = topic)
#         if form.is_valid():
#             form.save()
#             return redirect('edit_concept', concept_id=topic.id)
#     else:
#         form = ConceptForm(instance = topic)
#     return render(request, 'admin/edit_concept.html', {"form":form})
#
# @staff_member_required
# def add_subtitle(request, concept_id):
#     topic = get_object_or_404(Topic, id=concept_id)
#     if request.method == 'POST':
#         form = SubtitleForm(request.POST)
#         if form.is_valid():
#             subtitle = form.save(commit=False)
#             subtitle.topic = topic
#             subtitle.save()
#             # If using AJAX, you might return a JSON response here.
#             return redirect('edit_concept', concept_id=topic.id)
#     else:
#         form = SubtitleForm()
#     return render(request, 'admin/add_subtitle.html', {"form":form})

MyProject/templates/Tutorial/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="light">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tutorial</title>
<!--    For Dark Mode -->
    <link href="{% static 'dark_mode_switch/dark-mode-switch.css' %}" rel="stylesheet" type="text/css">
    {% block bootstrap5_extra_head %}{% endblock %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
<!--      /* Optional: Ensure the toggler icon is visible on our colored background */-->
      .navbar-toggler {
        border-color: rgba(255, 255, 255, 0.55);
      }
      .navbar-toggler-icon {
        filter: invert(1);
      }
      .html {
        scroll-behavior: smooth;
      }
<!--      /* Sidebar link hover effect: changes the background color slightly when hovered */-->
      .side-link:hover {
        background-color: rgba(0, 0, 0, 0.1);
        text-decoration: none;
      }
<!--/* -->
<!--  On medium (md) screens and larger, add a left margin to the main content container -->
<!--  so it doesn't overlap with the fixed left panel.-->
<!--  - This margin exactly equals the fixed panel's width (300px).-->
<!--*/-->
      @media (min-width: 768px) {
        .main-content {
          margin-left: 300px;
        }
      }
<!--      /* Sidebar container styling */-->
      .sidebar-panel {
        top: 70px;                     /* Start below the fixed navbar (assumed height 70px) */
        left: 0;                       /* Aligned flush with the left edge */
        width: 300px;                  /* Fixed width */
        height: calc(100vh - 70px);      /* Full viewport height minus the navbar */
        background-color: #f8f8f8;       /* Greyish white background */
        overflow-y: auto;              /* Add vertical scrolling if needed */
      }

<!--      /* Inner padding for the sidebar content */-->
      .sidebar-inner {
        padding: 1rem;                 /* Overall inner padding */
      }

<!--      /* List style reset (if needed) */-->
      .sidebar-list {
        margin: 0;
        padding: 0;
      }

<!--      /* Individual sidebar items; add a bit of margin spacing between items */-->
      .sidebar-item {
        margin-bottom: 0.5rem;
      }

<!--      /* Sidebar links default styling */-->
      .side-link {
        display: block;                    /* Make the link fill the container’s width */
        padding: 0.25rem 1rem;              /* Good, consistent padding */
        border-radius: 4px;                /* Slightly rounded corners */
        color: #333;                       /* Base text color */
        text-decoration: none;             /* Remove default underline */
        transition: background-color 0.3s ease;  /* Smooth transition for hover effect */
      }

<!--      /* Hover state: change background to a slightly darker grey */-->
      .side-link:hover {
        background-color: #e0e0e0;
      }

<!--      /* Active/selected state, for example if you add the class "active" server-side */-->
      .side-link.active,
      .side-link.selected {
        background-color: #417690;   /* Selected color */
        color: #fff;                 /* White text for contrast */
      }


      /* Index.html styles */
      .list-group-item:hover {
        background-color: var(--bs-list-group-hover-bg, #417690) !important;
      }
      @media (prefers-color-scheme: dark) {
        .list-group-item:hover {
          background-color: #417690 !important;
        }
      }
    </style>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-md fixed-top" style="background-color: #417690;">
      <div class="container-fluid">
        <!-- Left side: Button to open the offcanvas side panel -->
        <!-- <button class="btn me-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidePanel" aria-controls="sidePanel">
          <span class="navbar-toggler-icon"></span>
        </button> -->

        <!-- Brand Name -->
        <a class="navbar-brand" href="/"> Sₖ </a>

        <!-- Right side: Navbar toggle on small screens -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible navbar content (right aligned) -->
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <!-- Home Link -->
            <li class="nav-item">
              <a class="nav-link text-light" href="/">Home</a>
            </li>
            <!-- Tutorials Dropdown -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-light" href="#" id="tutorialsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Tutorials
              </a>
              <ul class="dropdown-menu" aria-labelledby="tutorialsDropdown">
<!--                <li><a class="dropdown-item" href="/topics">Tutorial</a></li>-->
<!--                <li><a class="dropdown-item" href="/topics">CyberSecurity</a></li>-->
<!--                <li><a class="dropdown-item" href="#">Py</a></li>-->
                  {% for concept in nav_concepts %}
                      <li>
                        <a class="dropdown-item" href="{% url 'index' concept.slug %}">{{ concept.title }}</a>
                      </li>
                  {% endfor %}
              </ul>
            <li class="nav-item">
              <a class="nav-link text-light" href="#">About Us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="#">Contact Us</a>
            </li>
            <li class="navbar-nav ms-auto">
                {% include 'dark_mode_switch/dark_mode_switch.html' %}
            </li>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {# block sidepanel #}
        <!-- Offcanvas Side Panel (opens from the left) -->
        <!-- <div class="offcanvas offcanvas-start" tabindex="-1" id="sidePanel" aria-labelledby="sidePanelLabel" style="background-color: #417690;" >
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="sidePanelLabel">Menu</h5>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div> -->
          <!-- <div class="offcanvas-body"> -->
            <!-- Same menu items as in the navbar -->
            <!-- <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link text-light" href="/">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light" href="#" id="offcanvasTutorialsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Tutorials
                </a>
                <ul class="dropdown-menu" aria-labelledby="offcanvasTutorialsDropdown"> -->
<!--                  <li><a class="dropdown-item" href="/topics">Tutorial</a></li>-->
<!--                  <li><a class="dropdown-item" href="/topics">CyberSecurity</a></li>-->
<!--                  <li><a class="dropdown-item" href="#">Python</a></li>-->
                  {# for concept in nav_concepts #}
                      <!-- <li>
                        <a class="dropdown-item" href="{# url 'index' concept.slug #}">{{ concept.title }}</a>
                      </li> -->
                  {# endfor #}
                <!-- </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="/about">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="#">Contact Us</a>
              </li>
            </ul>
          </div>
        </div> -->
    {# endblock #}
    <main>
{% block content %}
  <div class="container py-5">

    <!-- Hero -->
    <div class="text-center mb-5 mt-5 pt-5">
      <h1 class="display-4 fw-bold">Sₖ Tutorial</h1>
      <p class="lead text-muted">Choose a concept to start learning</p>
    </div>

    

    <!-- Optional: short description grid (clean & bootstrap-first) -->
    <div class="row g-3 justify-content-center">
      {% for concept in concepts %}
        <div class="col-12 col-md-6 col-lg-4">
          <a href="{% url 'index' concept_slug=concept.slug %}" class="text-decoration-none">
            <div class="card h-100 shadow-sm">
              <div class="card-body">
                <h5 class="card-title mb-1">{{ concept.title }}</h5>
                {% if concept.tagline %}
                  <p class="card-text text-muted small">{{ concept.tagline|truncatechars:100 }}</p>
                {% else %}
                  <p class="card-text text-muted small">Learn to Excel</p>
                {% endif %}
                <div class="mt-3 d-flex justify-content-between align-items-center">
                  <span class="badge bg-secondary">{{ concept.topic_set.count }} topics</span>
                  <small class="text-muted">Start →</small>
                </div>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>

  </div>
{% endblock %}
        <!-- <div class="container py-5"> -->
            <!-- <div class="text-center my-5"> -->
<!--      {# Main large heading using display-4 for a high-impact font size #}-->
             <!-- <h1 class="display-1"><strong>sₖ Tutorial</strong></h1> -->
<!--      {# A subheading using the lead class for a slightly lighter, descriptive tone #}-->
                <!-- <p class="display-6"><strong>Learn to Excel</strong></p> -->
<!--      {# The call-to-action button: btn-dark gives you a black button with white text; btn-lg for a larger button #}-->
<!--      <a href="#concepts-{{ concepts.order }}"  class="btn btn-dark btn-lg">Get Started</a>-->
            <!-- </div> -->
<!--    {# Future content: a list of items can be inserted here later #}-->
<!--    like add buttons for each course-->
        <!-- </div> -->
        
      </main>

    <!-- Bootstrap JS Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<!--  For Dark mode JS script-->
    {% block bootstrap5_extra_script %}{% endblock %}
    <script src="{% static 'dark_mode_switch/dark-mode-switch.js' %}"></script>
  </body>
</html>

MyProject/templates/Tutorial/baseC.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>{% block title %}sₖ Tutorial{% endblock %}</title>

  <!-- quick safe defaults to avoid flashes -->
  <style>
    html,body { background: #fff; color: #212529; }
    body { padding-top: 64px; } /* room for fixed navbar */
  </style>

  <!-- Bootstrap CSS (CDN) -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

  {% block extra_head %}{% endblock %}
</head>
<body>
  <!-- simple navbar -->
  <nav class="navbar navbar-expand-md fixed-top" style="background:#417690;">
    <div class="container-fluid">
      <a class="navbar-brand text-white fw-bold" href="{% url 'home' %}">Sₖ</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav"
              aria-controls="nav" aria-expanded="false" aria-label="Toggle">
        <span class="navbar-toggler-icon" style="filter: invert(1)"></span>
      </button>

      <div class="collapse navbar-collapse" id="nav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item"><a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">Tutorials</a>
            <ul class="dropdown-menu dropdown-menu-end">
              {% if nav_concepts %}
                {% for c in nav_concepts %}
                  <li><a class="dropdown-item" href="{% url 'index' concept_slug=c.slug %}">{{ c.title }}</a></li>
                {% endfor %}
              {% else %}
                <li><span class="dropdown-item-text text-muted">No concepts</span></li>
              {% endif %}
            </ul>
          </li>
          <li class="nav-item"><a class="nav-link text-white" href="#">About</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- optional secondary block (pages may fill it) -->
  {% block secondary %}{% endblock %}

  <!-- the content block: keep empty so children render their content -->
  <main>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </main>

  <!-- bootstrap bundle -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

  <!-- tiny script: make nav/pills active by URL -->
  <script>
    (function () {
      function markActive() {
        const current = location.pathname.replace(/\/$/, '');
        document.querySelectorAll('a').forEach(a => {
          try {
            const href = new URL(a.href, location.origin).pathname.replace(/\/$/, '');
            if (href === current) {
              a.classList.add('active');
              a.setAttribute('aria-current', 'page');
            } else {
              a.classList.remove('active');
              a.removeAttribute('aria-current');
            }
          } catch(e){}
        });
      }
      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', markActive);
      } else markActive();
    })();
  </script>

  {% block extra_script %}{% endblock %}
</body>
</html>

MyProject/templates/Tutorial/home.html
{% extends "Tutorial/base.html" %}
{% block title %}Home — Sₖ Tutorial{% endblock %}

{% block content %}
  <div class="container py-5">

    <!-- Hero -->
    <div class="text-center mb-4">
      <h1 class="display-4 fw-bold">Sₖ Tutorial</h1>
      <p class="lead text-muted">Choose a concept to start learning</p>
    </div>

    <!-- Pills: horizontal on md+, stacked on small screens -->
    <div class="d-flex flex-column flex-md-row flex-wrap gap-2 justify-content-center align-items-start mb-4">
      {% if concepts %}
        {% for concept in concepts %}
          <a href="{% url 'index' concept_slug=concept.slug %}"
            class="btn btn-outline-primary rounded-pill d-flex align-items-center px-3 py-2 concept-pill"
            title="{{ concept.title }}">
          </a>
          <!-- <a href="{% url 'index' concept_slug=concept.slug %}"
            class="btn btn-outline-primary rounded-pill d-flex align-items-center px-3 py-2"
            title="{{ concept.title }}">
            <span class="me-2">{{ concept.title }}</span>
            <span class="badge bg-primary ms-2">{{ concept.topic_set.count }}</span>
          </a> -->
        {% endfor %}
      {% else %}
        <div class="text-center text-muted">No concepts available yet.</div>
      {% endif %}
    </div>

    <!-- Optional: short description grid (clean & bootstrap-first) -->
    <div class="row g-3">
      {% for concept in concepts %}
        <div class="col-12 col-md-6 col-lg-4">
          <a href="{% url 'index' concept_slug=concept.slug %}" class="text-decoration-none">
            <div class="card h-100 shadow-sm">
              <div class="card-body">
                <h5 class="card-title mb-1">{{ concept.title }}</h5>
                {% if concept.short_description %}
                  <p class="card-text text-muted small">{{ concept.short_description|truncatechars:100 }}</p>
                {% else %}
                  <p class="card-text text-muted small">Short description not provided.</p>
                {% endif %}
                <div class="mt-3 d-flex justify-content-between align-items-center">
                  <span class="badge bg-secondary">{{ concept.topic_set.count }} topics</span>
                  <small class="text-muted">Start →</small>
                </div>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>

  </div>
{% endblock %}

MyProject/templates/Tutorial/post.html
{% extends 'Tutorial/base.html' %}

{% block title %}Admin page{% endblock %}
<!--Wanted to create a seperate form to add content in site but decide to use admin page!-->
{% block content %}
<form method="post" action="/postcontent/">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit", name="save">Publish</button>
<!--    <button type="draft", name="draft">Draft</button>-->
</form>